### ISSUE TITLE
Table parsing issues with parse_pubmed_table

### ISSUE THREAD

**Issue by octotus** [titipata/pubmed_parser#118] opened 2022-07-17 01:40 UTC
Using parse_pubmed_table with PMC535341.xml and PMC535340.xml (as test papers). In both cases, parse_pubmed_table is not retrieving table info. Other modules like parse_captions / paragraphs work fine.

Any hints at what am doing wrong will be helpful. Thanks.

**Comment by raypereda-gr** [comment] 2022-07-17 19:47
I suggest posting code on the pull request. Clearly explain what you expected, or wanted, with a test case. 

Additional nodes can be added to the parser.

**Comment by Michael-E-Rose** [comment] 2024-05-16 10:17
Duplicate of #119

**Closed by Michael-E-Rose** 2024-05-16 10:17 UTC
Labels: duplicate
